routes/web.php
<?php

//Auth::routes();
Route::post('/login', 'Auth\LoginController@login')->name('login');
Route::post('/register', 'Auth\RegisterController@register')->name('register');

Route::prefix('account')->as('account.')->middleware('user')->group(function () {
    Route::get('/profile', 'AccountController@profile')->name('profile');
});

Route::prefix('admin')->as('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::prefix('pages')->as('pages.')->group(function () {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/create', 'Admin\PageController@create')->name('create');
    });

    Route::prefix('users')->as('users.')->group(function () {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/create', 'Admin\UserController@create')->name('create');
    });

    Route::prefix('settings')->as('settings.')->group(function () {
        Route::get('/', 'Admin\SettingController@index')->name('index');
    });

    Route::prefix('menu')->as('menu.')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('index');
    });

    Route::prefix('testimonials')->as('testimonials.')->group(function () {
        Route::get('/', 'Admin\TestimonialController@index')->name('index');
    });

    Route::prefix('tests')->as('tests.')->group(function () {
        Route::get('/', 'Admin\TestController@index')->name('index');
    });

    Route::prefix('posts')->as('posts.')->group(function () {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/create', 'Admin\PostController@create')->name('create');
    });
});

Route::get('{slug?}', 'PageController@router')->where('slug', '(.*)');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Idealacity | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/jqvmap/jqvmap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('admin-assets/dist/css/adminlte.min.css') }}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/daterangepicker/daterangepicker.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('admin-assets/plugins/summernote/summernote-bs4.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('admin-assets/css/main.css') }}">
    @yield('css-section')
</head>
<body class="hold-transition sidebar-mini layout-fixed">

<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light bg-primary">
        <ul class="navbar-nav">
            <li class="nav-item humb_button">
                <a class="nav-link" data-widget="pushmenu" href="#">
                    <i class="fas fa-bars"></i>
                </a>
            </li>
        </ul>
        <a href="{{ route('admin.dashboard') }}" class="header_logo">Idealacity</a>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        @include('admin.includes.sidebar')
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @yield('content')

        <footer class="main-footer">
            <strong>Copyright © 2020 All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- /.content-wrapper -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('admin-assets/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('admin-assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('admin-assets/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('admin-assets/plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('admin-assets/plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('admin-assets/plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin-assets/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin-assets/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('admin-assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('admin-assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('admin-assets/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('admin-assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin-assets/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin-assets/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin-assets/dist/js/demo.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('admin-assets/plugins/select2/js/select2.full.min.js') }}"></script>

<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2();

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })
</script>

<script src="{{ asset('admin-assets/js/custom.js') }}"></script>

@yield('js-section')

</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ $page->seo_title ?? $page->title }}</title>
    <meta name="description" content="{{ $page->seo_description }}">

    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css">

    <link rel="stylesheet" href="{{ asset('css/main_anton.css') }}">
    <link rel="stylesheet" href="{{ asset('css/main_kolya.css') }}">

    <link rel="stylesheet" href="{{ asset('css/media_anton.css') }}">
    <link rel="stylesheet" href="{{ asset('css/media_artur.css') }}">
    <link rel="stylesheet" href="{{ asset('css/media_kolya.css') }}">

    <link rel="stylesheet" href="{{ asset('css/additional.css') }}">

    @yield('css-section')
</head>
<body>

<header>
    <div class="container">
        <div class="row">
            <div class="col-3 col-xl-3">
                <div class="logo">
                    <a href="{{ url('/') }}">
                        <img src="{{ asset('images/Logo.svg') }}" alt="">
                    </a>
                </div>
            </div>
            <div class="col-9 col-xl-9">
                <div class="wrapper-flex-a-center-j-end h-100-percent">
                    <nav class="header_nav">
                        <ul class="menu">
                            <li>
                                <a href="#" class="take_the_test_mob">Take the Test</a>
                            </li>
                            <li>
                                <a href="{{ auth()->check() ? (auth()->user()->isAdmin() ? route('admin.dashboard') : route('account.profile')) : route('account.profile') }}"
                                   {!! !auth()->check() ? 'data-fancybox data-src="#login_popup"' : '' !!}>
                                    {{ (auth()->check() and auth()->user()->isAdmin()) ? 'Dashboard' : 'My profile' }}
                                </a>
                            </li>
                            <li>
                                <a href="{{ url('/articles-and-videos') }}">Articles & Videos</a>
                            </li>
                            <li>
                                <a href="{{ url('/testimonials') }}">Testimonials</a>
                            </li>
                        </ul>
                    </nav>
                    <a href="#" class="btn">Take the Test</a>
                    <div class="user_box">
                        <img src="{{ asset('images/user_avatar.svg') }}" alt="">
                    </div>
                    <a href="" class="mob_menu_btn">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

@yield('content')

<footer class="">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="copyright">©2019 Luminary Press</div>
                <ul class="menu">
                    <li>
                        <a href="{{ url('/contact-us') }}">Contact Us</a>
                    </li>
                    <li>
                        <a href="{{ url('/terms-and-conditions') }}">Terms & Conditions</a>
                    </li>
                    <li>
                        <a href="{{ url('/privacy-policy') }}">Privacy policy</a>
                    </li>
                </ul>

                <ul class="menu_icon">
                    <li>
                        <a href="#">
                            <img src="{{ asset('images/svg/facebook.svg') }}" />
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{ asset('images/svg/youtube.svg') }}" />
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{ asset('images/svg/instagram.svg') }}" />
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{ asset('images/svg/twitter.svg') }}" />
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- Popups -->

<div class="register_popup" id="login_popup">
    <h3 class="popup_title">Sign In</h3>
    <form action="{{ route('login') }}" id="loginForm" class="register_popup_form">
        @csrf
        <div class="form_group">
            <input type="email" name="email" class="text_input" placeholder="Email">
        </div>
        <div class="form_group">
            <input type="password" name="password" class="text_input" placeholder="Password">
            <div class="invalid-feedback" data-field="email"></div>
        </div>
        <div class="form_group btn_wrpr">
            <button class="btn">Sign In</button>
        </div>
    </form>
</div>

<div class="register_popup" id="register_popup">
    <h3 class="popup_title">Register</h3>
    <p class="popup_subtitle">Please register to personalize your results</p>
    <form action="{{ route('register') }}" id="registerForm" class="register_popup_form">
        @csrf
        <div class="form_group">
            <input type="text" name="name" class="text_input" placeholder="Name">
            <div class="invalid-feedback" data-field="name"></div>
        </div>
        <div class="form_group">
            <input type="email" name="email" class="text_input" placeholder="Email">
            <div class="invalid-feedback" data-field="email"></div>
        </div>
        <div class="form_group">
            <input type="password" name="password" class="text_input" placeholder="Password">
            <div class="invalid-feedback" data-field="password"></div>
        </div>
        <div class="form_group">
            <div class="select">
                <select name="gender">
                    <option value="" selected disabled>Gender</option>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
            <div class="invalid-feedback" data-field="gender"></div>
        </div>
        <div class="form_group btn_wrpr">
            <button class="btn">Continue</button>
        </div>
    </form>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{{ asset('js/main.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>

@yield('js-section')

</body>
</html>