routes/web.php
<?php

//Auth::routes();
Route::post('/login', 'Auth\LoginController@login')->name('login');
Route::post('/register', 'Auth\RegisterController@register')->name('register');

Route::prefix('account')->as('account.')->middleware('user')->group(function () {
    Route::get('/profile', 'AccountController@profile')->name('profile');
});

Route::prefix('admin')->as('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

    Route::prefix('pages')->as('pages.')->group(function () {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/create', 'Admin\PageController@create')->name('create');
    });

    Route::prefix('users')->as('users.')->group(function () {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/create', 'Admin\UserController@create')->name('create');
    });

    Route::prefix('settings')->as('settings.')->group(function () {
        Route::get('/', 'Admin\SettingController@index')->name('index');
    });

    Route::prefix('menu')->as('menu.')->group(function () {
        Route::get('/', 'Admin\MenuController@index')->name('index');
    });

    Route::prefix('testimonials')->as('testimonials.')->group(function () {
        Route::get('/', 'Admin\TestimonialController@index')->name('index');
    });

    Route::prefix('tests')->as('tests.')->group(function () {
        Route::get('/', 'Admin\TestController@index')->name('index');
    });

    Route::prefix('posts')->as('posts.')->group(function () {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/create', 'Admin\PostController@create')->name('create');
    });
});

Route::get('{slug?}', 'PageController@router')->where('slug', '(.*)');

resources/views/admin/includes/sidebar.blade.php
<!-- Sidebar -->
<div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{{ asset('admin-assets/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">Alexander Pierce</a>
        </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
            data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
				 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-book"></i>
                    <p>
                        Pages
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('admin.pages.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All pages</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admin.pages.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Create new page</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-user"></i>
                    <p>
                        Users
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('admin.users.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All users</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admin.users.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Create new users</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.settings.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-cog"></i>
                    <p>
                        Settings
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.menu.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                        Menu
                    </p>
                </a>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fa fa-window-maximize"></i>
                    <p>
                        Blog
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{{ route('admin.posts.index') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>All posts</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admin.posts.create') }}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Create new post</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.testimonials.index') }}" class="nav-link">
                    <i class="nav-icon far fa-comment"></i>
                    <p>
                        Testimonials
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('admin.tests.index') }}" class="nav-link">
                    <i class="nav-icon fas fa-spell-check"></i>
                    <p>
                        Tests
                    </p>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-sign-out-alt"></i>
                    <p>
                        Logout
                    </p>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>
<!-- /.sidebar -->